import csv
import os
import time
import random
import requests
from dotenv import load_dotenv

load_dotenv()

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = "http://127.0.0.1:8888/callback"
SCOPE = "playlist-modify-public playlist-modify-private"

# ─── OAuth (opens browser for login) ─────────────────────────────────────────

def get_user_token():
    import spotipy
    from spotipy.oauth2 import SpotifyOAuth
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope=SCOPE,
    ))
    return sp

# ─── Search Spotify for a track ──────────────────────────────────────────────

def search_track(sp, artist, track):
    try:
        q = f"track:{track} artist:{artist}"
        results = sp.search(q=q, type="track", limit=1, market="US")
        items = results["tracks"]["items"]
        return items[0]["uri"] if items else None
    except Exception:
        return None

# ─── Add tracks to playlist in batches of 100 ────────────────────────────────

def add_in_batches(sp, playlist_id, uris):
    for i in range(0, len(uris), 100):
        batch = uris[i:i+100]
        sp.playlist_add_items(playlist_id, batch)
        time.sleep(0.5)

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("Spotify Playlist Creator\n")

    # Load discoveries
    discoveries = []
    with open("discoveries.csv", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            discoveries.append(row)

    print(f"Loaded {len(discoveries)} discovered tracks")

    # Shuffle so playlist isn't grouped by artist
    random.shuffle(discoveries)

    # Limit to a reasonable playlist size (change this if you want more/less)
    playlist_size = 100
    sample = discoveries[:playlist_size]
    print(f"Building a playlist of {playlist_size} tracks (shuffled from {len(discoveries)} total)")

    # Login to Spotify
    print("\nOpening Spotify login in your browser...")
    sp = get_user_token()
    user = sp.current_user()
    user_id = user["id"]
    print(f"Logged in as: {user['display_name']}")

    # Create playlist
    from datetime import date
    playlist_name = f"Discovery - {date.today().strftime('%B %d %Y')}"
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=False,
        description="Generated by SpotifyDiscovery - Last.fm + MusicBrainz powered recommendations"
    )
    playlist_id = playlist["id"]
    print(f"\nCreated playlist: '{playlist_name}'")

    # Search and add tracks
    found_uris = []
    not_found = []
    print(f"Searching Spotify for {len(sample)} tracks...")

    for i, row in enumerate(sample, 1):
        uri = search_track(sp, row["artist"], row["track"])
        if uri:
            found_uris.append(uri)
        else:
            not_found.append(f"{row['artist']} - {row['track']}")
        if i % 10 == 0:
            print(f"  {i}/{len(sample)} searched, {len(found_uris)} found so far...")
        time.sleep(0.1)

    print(f"\nFound {len(found_uris)} tracks on Spotify ({len(not_found)} not found)")

    if found_uris:
        add_in_batches(sp, playlist_id, found_uris)
        print(f"Added {len(found_uris)} tracks to '{playlist_name}'")
        print(f"Open Spotify and check your playlists!")
    else:
        print("No tracks found - something may be wrong with the search.")

    if not_found:
        print(f"\n{len(not_found)} tracks couldn't be found on Spotify (live recordings, regional, etc.)")

if __name__ == "__main__":
    main()
