"""Spotify playlist operations."""
import time

def get_liked_artists_and_tracks(sp):
    """Fetch user's liked songs and return (liked_artists set, liked_track_keys set)."""
    liked_artists = set()
    liked_tracks = set()
    offset = 0
    while True:
        results = sp.current_user_saved_tracks(limit=50, offset=offset)
        items = results.get("items", [])
        if not items:
            break
        for item in items:
            track = item.get("track")
            if not track:
                continue
            track_name = track["name"].strip().lower()
            for artist in track.get("artists", []):
                artist_name = artist["name"].strip().lower()
                liked_artists.add(artist_name)
                liked_tracks.add(f"{artist_name} - {track_name}")
        offset += 50
        if not results.get("next"):
            break
    return liked_artists, liked_tracks

def get_playlist_artists_and_tracks(sp, playlist_id):
    """Fetch tracks from a specific playlist."""
    liked_artists = set()
    liked_tracks = set()
    offset = 0
    while True:
        results = sp.playlist_items(playlist_id, limit=100, offset=offset)
        items = results.get("items", [])
        if not items:
            break
        for item in items:
            track = item.get("track")
            if not track:
                continue
            track_name = track["name"].strip().lower()
            for artist in track.get("artists", []):
                artist_name = artist["name"].strip().lower()
                liked_artists.add(artist_name)
                liked_tracks.add(f"{artist_name} - {track_name}")
        offset += 100
        if not results.get("next"):
            break
    return liked_artists, liked_tracks

def search_track(sp, artist, track):
    try:
        results = sp.search(q=f"track:{track} artist:{artist}", type="track", limit=1, market="US")
        items = results["tracks"]["items"]
        if items:
            t = items[0]
            return {
                "uri": t["uri"],
                "name": t["name"],
                "artist": t["artists"][0]["name"],
                "album": t["album"]["name"],
                "album_art": t["album"]["images"][1]["url"] if len(t["album"]["images"]) > 1 else None,
                "preview_url": t.get("preview_url"),
            }
        return None
    except Exception:
        return None

def push_to_spotify(sp, user_id, tracks, playlist_name):
    """Create a playlist and add tracks. Returns spotify playlist URL."""
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=False,
        description="Generated by Rabbithole Music - discover music you didn't know you needed"
    )
    playlist_id = playlist["id"]

    uris = [t["uri"] for t in tracks if t.get("uri")]
    for i in range(0, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i:i+100])
        time.sleep(0.3)

    return playlist["external_urls"]["spotify"], playlist_id
